site_name: push2HAL
nav:
  - Home: index.md
  - API wrapper: api.md
  - About: about.md
theme: readthedocs
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
