####*****************************************************************************************
####*****************************************************************************************
####*****************************************************************************************
#### Library part of push2HAL
#### Copyright - 2024 - Luc Laurent (luc.laurent@lecnam.net)
####
#### description available on https://github.com/luclaurent/push2HAL
####*****************************************************************************************
####*****************************************************************************************

from furl import furl


DEFAULT_NB_CHAR = 400
TXT_SEP = "++++++++++++++++++++++"

DEFAULT_CREDENTIALS_FILE = ".apihal"
DEFAULT_UPLOAD_FILE_NAME_PDF = "{}.pdf"  #'upload.pdf'
DEFAULT_UPLOAD_FILE_NAME_XML = "upload.xml"
DEFAULT_UPLOAD_FILE_NAME_ZIP = "upload"
DEFAULT_MAX_NUMBER_RESULTS = (
    100  # results to display when searching in archives-ouvertes.fr
)


DEFAULT_XML_SWORD_PACKAGING = furl("http://purl.org/net/sword-types/AOfr")
DEFAULT_CONTENT_DISPOSITION = "none"
DEFAULT_EXPORT_ARCHIVE = "false"
DEFAULT_EXPORT_PMC = "false"
DEFAULT_HIDE_REPEC = "false"
DEFAULT_HIDE_OAI = "false"
DEFAULT_ALLOW_COMPLETION = "false"
DEFAULT_HAL_TEST = "1"

DEFAULT_VALIDATION_XSD = "aofr.xsd"
DEFAULT_TEI_URL_NAMESPACE = furl("http://www.tei-c.org/ns/1.0")
DEFAULT_NAMESPACE_XML = {
    None: DEFAULT_TEI_URL_NAMESPACE.url
}  # , 'tei': 'http://www.tei-c.org/ns/1.0' , 'hal':'http://hal.archives-ouvertes.fr'} #{"tei": "http://www.tei-c.org/ns/1.0"}
DEFAULT_XML_LANG = "{http://www.w3.org/XML/1998/namespace}"
DEFAULT_ERROR_DESCRIPTION_SWORD_LOC = "sword:verboseDescription"
HAL_API_BASE = furl("https://api.archives-ouvertes.fr/")
HAL_API_URL = {
    "base": HAL_API_BASE.copy(),
    "search": HAL_API_BASE.set(path="search/").copy(),
    "anr": HAL_API_BASE.set(path="ref/anrproject/").copy(),
    "author": HAL_API_BASE.set(path="ref/author/").copy(),
    "authorstructure": HAL_API_BASE.set(path="ref/authorstructure/").copy(),
    "europeanproject": HAL_API_BASE.set(path="ref/europeanproject/").copy(),
    "doctype": HAL_API_BASE.set(path="ref/doctype/").copy(),
    "domain": HAL_API_BASE.set(path="ref/domain/").copy(),
    "instance": HAL_API_BASE.set(path="ref/instance/").copy(),
    "journal": HAL_API_BASE.set(path="ref/journal/").copy(),
    "metadata": HAL_API_BASE.set(path="ref/metadata/").copy(),
    "metadatalist": HAL_API_BASE.set(path="ref/metadatalist/").copy(),
    "structure": HAL_API_BASE.set(path="ref/structure/").copy(),
}

############################################################
############################################################
############################################################
## DOC
# https://api.archives-ouvertes.fr/docs/search
# https://api.archives-ouvertes.fr/docs/search/?schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_DOC = {
    "abstract_exact": "abstract_s",
    "abstract_unsensitive": "abstract_t",
    "abstract": "abstract_t",
    "classification_acm_2012": "acm2012_s",
    "classification_acm": "acm_s",
    "acronym_anr_exact": "anrProjectAcronym_s",
    "acronym_anr_exact_unsensitive": "anrProjectAcronym_sci",
    "acronym_anr_unsensitive": "anrProjectAcronym_t",
    "acronym_anr": "anrProjectAcronym_t",
    "call_acronym_anr_exact": "anrProjectCallAcronym_s",
    "call_acronym_anr_unsensitive": "anrProjectCallAcronym_t",
    "call_acronym_anr": "anrProjectCallAcronym_t",
    "call_title_anr_exact": "anrProjectCallTitle_s",
    "call_title_anr_unsensitive": "anrProjectCallTitle_t",
    "call_title_anr": "anrProjectCallTitle_t",
    "id_title_anr_facet": "anrProjectIdTitle_fs",
    "id_anr": "anrProjectId_i",
    "code_anr_ref_exact": "anrProjectReference_s",
    "code_anr_ref_unsensitive": "anrProjectReference_t",
    "code_anr_ref": "anrProjectReference_t",
    "nom_id_anr_facet": "anrProjectTitleId_fs",
    "name_anr_exact": "anrProjectTitle_s",
    "name_anr_unsensitive": "anrProjectTitle_t",
    "name_anr": "anrProjectTitle_t",
    "validity_anr": "anrProjectValid_s",
    "year_anr": "anrProjectYearDate_s",
    "year_anr_format": "anrProjectYearDate_tdate",
    "search_anr_unsensitive": "anrProject_t",
    "search_anr": "anrProject_t",
    "id_arxiv_nosep": "arxivId_id",
    "id_arxiv": "arxivId_s",
    "audience_exact": "audience_s",
    "audience_unsensitive": "audience_t",
    "audience": "audience_t",
    "author_idhal_facet": "authAlphaLastNameFirstNameIdHal_fs",
    "author_internal_facet": "authAlphaLastNameFirstNameId_fs",
    "email_domain": "authEmailDomain_s",
    "email_address_md4": "authEmail_s",
    "author_first_name_exact": "authFirstName_s",
    "author_first_name_ex_unsensitive": "authFirstName_sci",
    "author_first_name_unsensitive": "authFirstName_t",
    "author_first_name": "authFirstName_t",
    # "":"authFullNameFormIDPersonIDIDHal_fs",
    # "":"authFullNameIdFormPerson_fs",
    "author_full_idhal_facet": "authFullNameIdHal_fs",
    "author_full_internal_facet": "authFullNameId_fs",
    "author_ful_full_facet": "authFullNamePersonIDIDHal_fs",
    "author_full_name_exact": "authFullName_s",
    "author_full_name_ex_unsensitive": "authFullName_sci",
    "author_full_name_unsensitive": "authFullName_t",
    "author_full_name": "authFullName_t",
    "author_formid-personid": "authIdFormPerson_s",
    "author_idform": "authIdForm_i",
    "author_internal_full_name_facet": "authIdFullName_fs",
    # "":"authIdHalFullName_fs",
    "personid": "authIdHal_i",
    "author_idhal": "authIdHal_s",
    "author_internal_full_structprim_facet": "authIdHasPrimaryStructure_fs",
    "author_internal_full_struct_facet": "authIdHasStructure_fs",
    "author_internal_fast_first_facet": "authIdLastNameFirstName_fs",
    "author_idperson": "authIdPerson_i",
    "author_id": "authId_i",
    "author_last_first_personid_facet": "authLastNameFirstNameIdHalPersonid_fs",
    "author_last_first_exact": "authLastNameFirstName_s",
    "author_last_name_exact": "authLastName_s",
    "author_last_name_ex_unsensitive": "authLastName_sci",
    "author_last_name_unsensitive": "authLastName_t",
    "author_last_name": "authLastName_t",
    "author_middle_name_exact": "authMiddleName_s",
    "author_middle_name_ex_unsensitive": "authMiddleName_sci",
    "author_middle_name": "authMiddleName_t",
    "author_funder_id": "authOrganismId_i",
    "author_funder_exact": "authOrganism_s",
    "author_funder_unsensitive": "authOrganism_t",
    "author_funder": "authOrganism_t",
    "author_job_exact": "authQuality_s",
    "auhtor_struct_id": "authStructId_i",
    "auhtor_url": "authUrl_s",
    "author_last_auto_complete": "auth_autocomplete",
    # "":"auth_sort",
    "author_multi": "auth_t",
    "authority_thesis_exact": "authorityInstitution_s",
    "authority_thesis_unsensitive": "authorityInstitution_t",
    "authority_thesis": "authorityInstitution_t",
    # "":"baseMap_s",
    # "":"baseMap_t",
    "book_title_exact": "bookTitle_s",
    "book_title_unsensitive": "bookTitle_t",
    "book_title": "bookTitle_t",
    # "":"campusaar_context_t",
    # "":"campusaar_genre_t",
    "citation_full_exact": "citationFull_s",
    "citation_abbr_exact": "citationRef_s",
    "city_exact": "city_s",
    "city_unsensitive": "city_t",
    "city": "city_t",
    "classification_exact": "classification_s",
    "classification_unsensitive": "classification_t",
    "classification": "classification_t",
    "collection_category_code_facet": "collCategoryCodeName_fs",
    "collection_category_exact": "collCategory_s",
    "collection_code_facet": "collCodeName_fs",
    "collection_code": "collCode_s",
    "collection_id_facet": "collIdName_fs",
    "collection_id": "collId_i",
    "collection_code_child_facet": "collIsChildOfColl_fs",
    "collection_code_category_parent_facet": "collIsParentOfCategoryColl_fs",
    "collection_code_parent_facet": "collIsParentOfColl_fs",
    "collection_name_code_facet": "collNameCode_fs",
    "collection_name_id_facet": "collNameId_fs",
    "collection_name_exact": "collName_s",
    "collection_name_unsensitive": "collName_t",
    "collection_name": "collName_t",
    "collab_exact": "collaboration_s",
    "collab_ex_unsensitive": "collaboration_sci",
    "collab_unsensitive": "collaboration_t",
    "collab": "collaboration_t",
    "collection_multi": "collection_t",
    "comment_exact": "comment_s",
    "comment_unsensitive": "comment_t",
    "comment": "comment_t",
    "committee_exact": "committee_s",
    "committee_unsensitive": "committee_t",
    "committee": "committee_t",
    "conf_end_day": "conferenceEndDateD_i",
    "conf_end_month": "conferenceEndDateM_i",
    "conf_end_year": "conferenceEndDateY_i",
    "conf_end_date": "conferenceEndDate_s",
    "conf_end_date_format": "conferenceEndDate_tdate",
    "conf_organizer_exact": "conferenceOrganizer_s",
    "conf_organizer_unsensitive": "conferenceOrganizer_t",
    "conf_organizer": "conferenceOrganizer_t",
    "conf_start_day": "conferenceStartDateD_i",
    "conf_start_month": "conferenceStartDateM_i",
    "conf_start_year": "conferenceStartDateY_i",
    "conf_start_date": "conferenceStartDate_s",
    "conf_start_date_format": "conferenceStartDate_tdate",
    "conf_title_exact": "conferenceTitle_s",
    "conf_title_ex_unsensitive": "conferenceTitle_sci",
    "conf_title_unsensitive": "conferenceTitle_t",
    "conf_title": "conferenceTitle_t",
    "conf_multi": "conference_t",
    "contributor_name_internal_facet": "contributorFullNameId_fs",
    "contributor_full_name_exact": "contributorFullName_s",
    "contributor_full_name_unsensitive": "contributorFullName_t",
    "contributor_full_name": "contributorFullName_t",
    "contributor_internal_name_facet": "contributorIdFullName_fs",
    "contributor_internal_id": "contributorId_i",
    "gps_coordinates": "coordinates_s",
    "country_exact": "country_s",
    "country_unsensitive": "country_t",
    "country": "country_t",
    "credit_exact": "credit_s",
    "credit_unsensitive": "credit_t",
    "credit": "credit_t",
    "date_last_indexed": "dateLastIndexed_tdate",
    "defense_date_day": "defenseDateD_i",
    "defense_date_month": "defenseDateM_i",
    "defense_date_year": "defenseDateY_i",
    "defense_date": "defenseDate_s",
    "defense_date_format": "defenseDate_tdate",
    "degree_exact": "degreeType_s",
    "degree_unsensitive": "degreeType_t",
    "degree": "degreeType_t",
    "department_acronym_exact": "deptStructAcronym_s",
    "department_acronym_ex_unsensitive": "deptStructAcronym_sci",
    "department_unsensitive": "deptStructAcronym_t",
    "department": "deptStructAcronym_t",
    "department_address": "deptStructAddress_s",
    "department_code_exact": "deptStructCode_s",
    "department_code_ex_unsensitive": "deptStructCode_sci",
    "department_code_unsensitive": "deptStructCode_t",
    "department_code": "deptStructCode_t",
    "department_country": "deptStructCountry_s",
    "department_idhal_name_facet": "deptStructIdName_fs",
    "department_id": "deptStructId_i",
    "department_child_facet": "deptStructIsChildOf_fs",
    "department_parent_facet": "deptStructIsParentOf_fs",
    "department_name_id_facet": "deptStructNameId_fs",
    "department_one_name_facet": "deptStructName_fs",
    "department_name_exact": "deptStructName_s",
    "department_name_ex_unsensitive": "deptStructName_sci",
    "department_name_unsensitive": "deptStructName_t",
    "department_name": "deptStructName_t",
    "department_type": "deptStructType_s",
    "department_validity": "deptStructValid_s",
    "description": "description_s",
    "phd_director_exact": "director_s",
    "phd_director_unsensitive": "director_t",
    "phd_director": "director_t",
    "subtype_doc": "docSubType_s",
    "type_doc": "docType_s",
    "id": "docid",
    "doi_nosep": "doiId_id",
    "doi": "doiId_s",
    "domain_all_codes": "domainAllCode_s",
    "domain_exact": "domain_s",
    "domain_unsensitive": "domain_t",
    "domain": "domain_t",
    "epub_date_day": "ePublicationDateD_i",
    "epub_date_month": "ePublicationDateM_i",
    "epub_date_year": "ePublicationDateY_i",
    "epub_date": "ePublicationDate_s",
    "epub_date_format": "ePublicationDate_tdate",
    "ensam_id": "ensamId_id",
    "ensam_id_exact": "ensamId_s",
    "europeanproject_acronym_exact": "europeanProjectAcronym_s",
    "europeanproject_acronym_ex_unsensitive": "europeanProjectAcronym_sci",
    "europeanproject_acronym_unsensitive": "europeanProjectAcronym_t",
    "europeanproject_acronym": "europeanProjectAcronym_t",
    "europeanproject_callid_exact": "europeanProjectCallId_s",
    "europeanproject_callid_unsensitive": "europeanProjectCallId_t",
    "europeanproject_callid": "europeanProjectCallId_t",
    "europeanproject_date_end": "europeanProjectEndDate_s",
    "europeanproject_funding": "europeanProjectFinancing_s",
    "europeanproject_id_title_facet": "europeanProjectIdTitle_fs",
    "europeanproject_id": "europeanProjectId_i",
    "europeanproject_ref_exact": "europeanProjectReference_s",
    "europeanproject_ref_unsensitive": "europeanProjectReference_t",
    "europeanproject_ref": "europeanProjectReference_t",
    "europeanproject_date_start": "europeanProjectStartDate_s",
    "europeanproject_title_id_facet": "europeanProjectTitleId_fs",
    "europeanproject_title_exact": "europeanProjectTitle_s",
    "europeanproject_title_unsensitive": "europeanProjectTitle_t",
    "europeanproject_title": "europeanProjectTitle_t",
    "europeanproject_validity": "europeanProjectValid_s",
    "europeanproject_multi": "europeanProject_t",
    "annexe_audio": "fileAnnexesAudio_s",
    "annexe_figure": "fileAnnexesFigure_s",
    "annexe_video": "fileAnnexesVideo_s",
    "annexe_urls": "fileAnnexes_s",
    "annexe_url_main": "fileMainAnnex_s",
    "file_url_main": "fileMain_s",
    "file_type": "fileType_s",
    "file_urls": "files_s",
    "pdf_fulltext": "fulltext_t",
    "funding_exact": "funding_s",
    "funding_unsensitive": "funding_t",
    "funding": "funding_t",
    "doc_idhal_old": "halIdSameAs_s",
    "doc_idhal_nosep": "halId_id",
    "doc_idhal": "halId_s",
    "hec_ranking_exact": "hec_ranking_s",
    "hec_ranking_unsensitive": "hec_ranking_t",
    "hec_ranking": "hec_ranking_t",
    "period_historic_exact": "historicalPeriod_s",
    "period_historic_unsensitive": "historicalPeriod_t",
    "period_historic": "historicalPeriod_t",
    "doc_id_multi": "identifiers_id",
    "image_type_exact": "imageType_s",
    "image_type_unsensitive": "imageType_t",
    "image_type": "imageType_t",
    "in_press_bool": "inPress_bool",
    # "":"inputType_s",
    # "":"inraeThesaurusAltLabel_local_s",
    # "":"inraeThesaurusCode_local_s",
    # "":"inraeThesaurusPrefLabel_local_s",
    "structure_acronym_exact": "instStructAcronym_s",
    "structure_acronym_ex_unsensitive": "instStructAcronym_sci",
    "structure_acronym_unsensitive": "instStructAcronym_t",
    "structure_acronym_": "instStructAcronym_t",
    "structure_address": "instStructAddress_s",
    "structure_code_exact": "instStructCode_s",
    "structure_code_ex_unsensitive": "instStructCode_sci",
    "structure_code_unsensitive": "instStructCode_t",
    "structure_code": "instStructCode_t",
    "structure_country": "instStructCountry_s",
    "structure_id_name_facet": "instStructIdName_fs",
    "structure_id": "instStructId_i",
    "structure_child_facet": "instStructIsChildOf_fs",
    "structure_parent_facet": "instStructIsParentOf_fs",
    "structure_name_id_facet": "instStructNameId_fs",
    "structure_one_name_facet": "instStructName_fs",
    "structure_name_exact": "instStructName_s",
    "structure_name_ex_unsensitive": "instStructName_sci",
    "structure_name_unsensitive": "instStructName_t",
    "structure_name": "instStructName_t",
    "structure_type": "instStructType_s",
    "structure_validity": "instStructValid_s",
    "hal_instance": "instance_s",
    "invited_communication_exact": "invitedCommunication_s",
    "invited_communication_unsensitive": "invitedCommunication_t",
    "invited_communication": "invitedCommunication_t",
    # "":"irThesaurusAcronym_s",
    # "":"irThesaurusId_s",
    # "":"irThesaurusName_s",
    "ird_id": "irdId_id",
    "ird_id_exact": "irdId_s",
    "irstea_id": "irsteaId_id",
    "irstea_id_exact": "irsteaId_s",
    "isbn_id": "isbn_id",
    "isbn_unsensitive": "isbn_s",
    "isbn": "isbn_s",
    "issue_number": "issue_s",
    "classification_jel_exact": "jel_s",
    "classification_jel_unsensitive": "jel_t",
    "classification_jel": "jel_t",
    "journal_date": "journalDate_s",
    "journal_doi_root": "journalDoiRoot_s",
    "journal_eissn": "journalEissn_s",
    "journal_id_title_facet": "journalIdTitle_fs",
    "journal_id": "journalId_i",
    "journal_issn": "journalIssn_s",
    "journal_publisher_exact": "journalPublisher_s",
    "journal_publisher_unsensitive": "journalPublisher_t",
    "journal_publisher": "journalPublisher_t",
    "journal_sherpa_color": "journalSherpaColor_s",
    "journal_sherpa_condition": "journalSherpaCondition_s",
    "journal_sherpa_date": "journalSherpaDate_s",
    "journal_sherpa_post_authorisations": "journalSherpaPostPrint_s",
    "journal_sherpa_post_restrictions": "journalSherpaPostRest_s",
    "journal_sherpa_": "journalSherpaPrePrint_s",
    "journal_sherpa_": "journalSherpaPreRest_s",
    "journal_title_abbe_exact": "journalTitleAbbr_s",
    "journal_title_abbr_ex_unsensitive": "journalTitleAbbr_sci",
    "journal_title_abbr_unsensitive": "journalTitleAbbr_t",
    "journal_title_abbr": "journalTitleAbbr_t",
    "journal_title_name_id_facet": "journalTitleId_fs",
    "journal_title_exact": "journalTitle_s",
    "journal_title_unsensitive": "journalTitle_t",
    "journal_title": "journalTitle_t",
    "journal_url": "journalUrl_s",
    "journal_validity": "journalValid_s",
    "journal_multi": "journal_t",
    "keyword_auto_complete": "keyword_autocomplete",
    "keyword_exact": "keyword_s",
    "keyword_ex_unsensitive": "keyword_sci",
    "keyword_unsensitive": "keyword_t",
    "keyword": "keyword_t",
    # "":"laas_directorEmail_s",
    # "":"laas_renatech_s",
    # "":"laas_renatech_t",
    "lab_acronym_exact": "labStructAcronym_s",
    "lab_acronym_ex_unsensitive": "labStructAcronym_sci",
    "lab_acronym_unsensitive": "labStructAcronym_t",
    "lab_acronym": "labStructAcronym_t",
    "lab_address": "labStructAddress_s",
    "lab_code_exact": "labStructCode_s",
    "lab_code_ex_unsensitive": "labStructCode_sci",
    "lab_code_unsensitive": "labStructCode_t",
    "lab_code": "labStructCode_t",
    "lab_country": "labStructCountry_s",
    "lab_id_name_facet": "labStructIdName_fs",
    "lab_id": "labStructId_i",
    "lab_child_facet": "labStructIsChildOf_fs",
    "lab_parent_facet": "labStructIsParentOf_fs",
    "lab_name_id_facet": "labStructNameId_fs",
    "lab_": "labStructName_fs",
    "lab_name_exact": "labStructName_s",
    "lab_name_ex_unsensitive": "labStructName_sci",
    "lab_name_unsensitive": "labStructName_t",
    "lab_name": "labStructName_t",
    "lab_type": "labStructType_s",
    "lab_validity": "labStructValid_s",
    "label_bibtex": "label_bibtex",
    "label_coins": "label_coins",
    "label_endnote": "label_endnote",
    "label_ref": "label_s",
    "label_xml": "label_xml",
    "language_format_exact": "language_s",
    "language_unsensitive": "language_t",
    "language": "language_t",
    "lecture_name": "lectureName_s",
    "lecture_level_exact": "lectureType_s",
    "lecture_level_unsensitive": "lectureType_t",
    "lecture_level": "lectureType_t",
    # "":"length_i",
    "licence_exact": "licence_s",
    "licence_unsensitive": "licence_t",
    "licence_": "licence_t",
    "external_id_exact": "linkExtId_s",
    "external_id_unsensitive": "linkExtUrl_s",
    "external_id": "linkExtUrl_s",
    "internal_ref_exact": "localReference_s",
    "internal_ref_unsensitive": "localReference_t",
    "internal_ref": "localReference_t",
    "gps_coordinates": "location",
    "gps_latitude": "location_0_coordinate",
    "gps_longitude": "location_1_coordinate",
    "classification_mesh_exact": "mesh_s",
    "classification_mesh_unsensitive": "mesh_t",
    "classification_mesh": "mesh_t",
    "modification_date_day": "modifiedDateD_i",
    "modification_date_month": "modifiedDateM_i",
    "modification_date_year": "modifiedDateY_i",
    "modification_date": "modifiedDate_s",
    "modification_date_format": "modifiedDate_tdate",
    "phd_number_id": "nntId_id",
    "phd_number_s": "nntId_s",
    "number_id": "number_id",
    "number_s": "number_s",
    "oatao_id": "oatad_id",
    "oatao_s": "oataoId_s",
    # "":"oldDocType_s",
    "open_access_bool": "openAccess_bool",
    "other_type": "otherType_s",
    # "":"overlayService_s",
    "owners": "owners_i",
    "page": "page_s",
    "peer_reviewing_exact": "peerReviewing_s",
    "peer_review_unsensitive": "peerReviewing_t",
    "peer_review": "peerReviewing_t",
    "popular_exact": "popularLevel_s",
    "popular_unsensitive": "popularLevel_t",
    "popular": "popularLevel_t",
    "primary_domain": "primaryDomain_s",
    "proceedings_exact": "proceedings_s",
    "proceedings_unsensitive": "proceedings_t",
    "proceedings": "proceedings_t",
    "production_date_day": "producedDateD_i",
    "production_date_month": "producedDateM_i",
    "production_date_year": "producedDateY_i",
    "production_date": "producedDate_s",
    "production_date_format": "producedDate_tdate",
    "publication_date_day": "publicationDateD_i",
    "publication_date_month": "publicationDateM_i",
    "publication_date_year": "publicationDateY_i",
    "publication_date": "publicationDate_s",
    "publication_date_format": "publicationDate_tdate",
    "publication_location_exact": "publicationLocation_s",
    "publication_location_unsensitive": "publicationLocation_t",
    "publication_location": "publicationLocation_t",
    "publisher_link": "publisherLink_s",
    "publisher_exact": "publisher_s",
    "publisher_unsensitive": "publisher_t",
    "publisher_": "publisher_t",
    "pubmed_id": "pubmedId_id",
    "pubmed_id_s": "pubmedId_s",
    "release_date_day": "releasedDateD_i",
    "release_date_month": "releasedDateM_i",
    "release_date_year": "releasedDateY_i",
    "release_date": "releasedDate_s",
    "release_date_format": "releasedDate_tdate",
    "report_type_exact": "reportType_s",
    "report_type_unsensitive": "reportType_t",
    "report_type": "reportType_t",
    "reaserach_data_doi": "researchData_s",
    "grp_struct_acronym_exact": "rgrpInstStructAcronym_s",
    "grp_struct_acronym_ex_unsensitive": "rgrpInstStructAcronym_sci",
    "grp_struct_acronym_unsensitive": "rgrpInstStructAcronym_t",
    "grp_struct_acronym": "rgrpInstStructAcronym_t",
    "grp_struct_address": "rgrpInstStructAddress_s",
    "grp_struct_code_exact": "rgrpInstStructCode_s",
    "grp_struct_code_ex_unsensitive": "rgrpInstStructCode_sci",
    "grp_struct_code_unsensitive": "rgrpInstStructCode_t",
    "grp_struct_code": "rgrpInstStructCode_t",
    "grp_struct_country": "rgrpInstStructCountry_s",
    "grp_struct_id_name_facet": "rgrpInstStructIdName_fs",
    "grp_struct_id": "rgrpInstStructId_i",
    "grp_struct_child_facet": "rgrpInstStructIsChildOf_fs",
    "grp_struct_parent_facet": "rgrpInstStructIsParentOf_fs",
    "grp_struct_name_id_facet": "rgrpInstStructNameId_fs",
    "grp_struct_name_id_facetb": "rgrpInstStructName_fs",
    "grp_struct_name_exact": "rgrpInstStructName_s",
    "grp_struct_name_ex_unsensitive": "rgrpInstStructName_sci",
    "grp_struct_name_unsensitive": "rgrpInstStructName_t",
    "grp_struct_name": "rgrpInstStructName_t",
    "grp_struct_type": "rgrpInstStructType_s",
    "grp_struct_validity": "rgrpInstStructValid_s",
    "grp_lab_acronym_exact": "rgrpLabStructAcronym_s",
    "grp_lab_acronym_ex_unsensitive": "rgrpLabStructAcronym_sci",
    "grp_lab_acronym_unsensitive": "rgrpLabStructAcronym_t",
    "grp_lab_acronym": "rgrpLabStructAcronym_t",
    "grp_lab_address": "rgrpLabStructAddress_s",
    "grp_lab_code_exact": "rgrpLabStructCode_s",
    "grp_lab_code_ex_unsensitive": "rgrpLabStructCode_sci",
    "grp_lab_code_unsensitive": "rgrpLabStructCode_t",
    "grp_lab_code_": "rgrpLabStructCode_t",
    "grp_lab_country": "rgrpLabStructCountry_s",
    "grp_lab_id_name_facet": "rgrpLabStructIdName_fs",
    "grp_lab_id": "rgrpLabStructId_i",
    "grp_lab_child_facet": "rgrpLabStructIsChildOf_fs",
    "grp_lab_parent_facet": "rgrpLabStructIsParentOf_fs",
    "grp_lab_name_id_facet": "rgrpLabStructNameId_fs",
    "grp_lab_name_id_facetb": "rgrpLabStructName_fs",
    "grp_lab_name_exact": "rgrpLabStructName_s",
    "grp_lab_name_ex_unsensitive": "rgrpLabStructName_sci",
    "grp_lab_name_unsensitive": "rgrpLabStructName_t",
    "grp_lab_name": "rgrpLabStructName_t",
    "grp_lab_type": "rgrpLabStructType_s",
    "grp_lab_validity": "rgrpLabStructValid_s",
    "team_acronym_exact": "rteamStructAcronym_s",
    "team_acronym_ex_unsensitive": "rteamStructAcronym_sci",
    "team_acronym_unsensitive": "rteamStructAcronym_t",
    "team_acronym": "rteamStructAcronym_t",
    "team_address": "rteamStructAddress_s",
    "team_code_exact": "rteamStructCode_s",
    "team_code_ex_unsensitive": "rteamStructCode_sci",
    "team_code_unsensitive": "rteamStructCode_t",
    "team_code": "rteamStructCode_t",
    "team_country": "rteamStructCountry_s",
    "team_id_name": "rteamStructIdName_fs",
    "team_id": "rteamStructId_i",
    "team_child_facet": "rteamStructIsChildOf_fs",
    "team_parent_facet": "rteamStructIsParentOf_fs",
    "team_name_id_facet": "rteamStructNameId_fs",
    "team_name_id_facetb": "rteamStructName_fs",
    "team_name_exact": "rteamStructName_s",
    "team_name_ex_unsensitive": "rteamStructName_sci",
    "team_name_unsensitive": "rteamStructName_t",
    "team_name": "rteamStructName_t",
    "team_type": "rteamStructType_s",
    "team_validity": "rteamStructValid_s",
    "scale_exact": "scale_s",
    "scale_unsensitive": "scale_t",
    "scale": "scale_t",
    "science_po_id": "sciencespoId_id",
    "science_po_id_s": "sciencespoId_s",
    "scientific_editor_exact": "scientificEditor_s",
    "scientific_editor_unsensitive": "scientificEditor_t",
    "scientific_editor": "scientificEditor_t",
    "see_also": "seeAlso_s",
    "self_archiving_bool": "selfArchiving_bool",
    "serie_title_exact": "serie_s",
    "serie_title_unsensitive": "serie_t",
    "serie_title": "serie_t",
    "serie_editor_exact": "seriesEditor_s",
    "serie_editor_unsensitive": "seriesEditor_t",
    "serie_editor": "seriesEditor_t",
    "gate_id": "sid_i",
    "soft_code_repository_exact": "softCodeRepository_s",
    "sosoft_code_repository_unsensitive": "softCodeRepository_t",
    "sosoft_code_repository": "softCodeRepository_t",
    "soft_dev_status_exact": "softDevelopmentStatus_s",
    "soft_dev_status_unsensitive": "softDevelopmentStatus_t",
    "soft_dev_status": "softDevelopmentStatus_t",
    "soft_platform_exact": "softPlatform_s",
    "soft_platform_unsensitive": "softPlatform_t",
    "soft_platform": "softPlatform_t",
    "soft_language_": "softProgrammingLanguage_s",
    "soft_language_": "softProgrammingLanguage_t",
    "soft_run_platform_": "softRuntimePlatform_s",
    "soft_run_platform_": "softRuntimePlatform_t",
    "soft_version_": "softVersion_s",
    "soft_version_": "softVersion_t",
    "source": "source_s",
    "status": "status_i",
    "struct_acronym_exact": "structAcronym_s",
    "struct_acronym_ex_unsensitive": "structAcronym_sci",
    "struct_acronym_unsensitive": "structAcronym_t",
    "struct_acronym": "structAcronym_t",
    "struct_address": "structAddress_s",
    "struct_code_exact": "structCode_s",
    "struct_code_ex_unsensitive": "structCode_sci",
    "struct_code_unsensitive": "structCode_t",
    "struct_code": "structCode_t",
    "struct_country_exact": "structCountry_s",
    "struct_country_unsensitive": "structCountry_t",
    "struct_country_": "structCountry_t",
    # "struct_":"structHasAlphaAuthIdHalPersonid_fs",
    # "struct_":"structHasAlphaAuthIdHal_fs",
    "struct_name_id_name_id_facet": "structHasAlphaAuthId_fs",
    # "struct_":"structHasAuthIdHalPersonid_s",
    # "struct_":"structHasAuthIdHal_fs",
    "struct_id_name_id_name_facet": "structHasAuthId_fs",
    "struct_id_name_facet": "structIdName_fs",
    "struct_id": "structId_i",
    "struct_child_facet": "structIsChildOf_fs",
    # "struct_":"structIsParentOfType_fs",
    "struct_parent_facet": "structIsParentOf_fs",
    "struct_one_id_facet": "structNameId_fs",
    "struct_name_facet": "structName_fs",
    "struct_name_exact": "structName_s",
    "struct_name_ex_unsensitive": "structName_sci",
    "struct_name_unsensitive": "structName_t",
    "struct_name": "structName_t",
    # "struct_":"structPrimaryHasAlphaAuthIdHalPersonid_fs",
    # "struct_":"structPrimaryHasAlphaAuthIdHal_fs",
    # "struct_":"structPrimaryHasAlphaAuthId_fs",
    # "struct_":"structPrimaryHasAuthIdHal_fs",
    # "struct_":"structPrimaryHasAuthId_fs",
    "struct_type": "structType_s",
    "struct_validity": "structValid_s",
    "struct_multi": "structure_t",
    "subtitle_exact": "subTitle_s",
    "subtitle_unsensitive": "subTitle_t",
    "subtitle": "subTitle_t",
    "type": "submitType_s",
    "submit_date_day": "submittedDateD_i",
    "submit_date_month": "submittedDateM_i",
    "submit_date_year": "submittedDateY_i",
    "submit_date": "submittedDate_s",
    "submit_date_format": "submittedDate_tdate",
    "text_search_unsensitive": "text",
    "text_full_unsensitive": "text_fulltext",
    "text_full": "text_fulltext",
    "thesis_school_exact": "thesisSchool_s",
    "thesis_school_unsensitive": "thesisSchool_t",
    "thesis_school": "thesisSchool_t",
    "thumb_id": "thumbId_i",
    "title_auto_complete": "title_autocomplete",
    "title_exact": "title_s",
    "title_sort": "title_sort",
    "title_unempty": "title_st",
    "title_unsensitive": "title_t",
    "title": "title_t",
    "annexe_type_exact": "typeAnnex_s",
    "annexe_type_unsensitive": "typeAnnex_t",
    "annexe_type": "typeAnnex_t",
    "type_exact": "type_s",
    "type_unsensitive": "type_t",
    "type": "type_t",
    "uri": "uri_s",
    # "":"urlFulltextEsr_s",
    "version": "version_i",
    "volume": "volume_s",
    "writing_date_day": "writingDateD_i",
    "writing_date_month": "writingDateM_i",
    "writing_date_year": "writingDateY_i",
    "writing_date": "writingDate_s",
    "writing_date_format": "writingDate_tdate",
}
HAL_API_ALLOWED_RETURN_FIELDS_DOC = {
    "abstract_exact": "abstract_s",
    "classification_acm_2012": "acm2012_s",
    "classification_acm": "acm_s",
    "acronym_anr_exact": "anrProjectAcronym_s",
    "call_acronym_anr_exact": "anrProjectCallAcronym_s",
    "call_title_anr_exact": "anrProjectCallTitle_s",
    "id_title_anr_facet": "anrProjectIdTitle_fs",
    "code_anr_ref_exact": "anrProjectReference_s",
    "nom_id_anr_facet": "anrProjectTitleId_fs",
    "name_anr_exact": "anrProjectTitle_s",
    "validity_anr": "anrProjectValid_s",
    "year_anr": "anrProjectYearDate_s",
    "id_arxiv": "arxivId_s",
    "audience_exact": "audience_s",
    "author_idhal_facet": "authAlphaLastNameFirstNameIdHal_fs",
    "author_internal_facet": "authAlphaLastNameFirstNameId_fs",
    "email_domain": "authEmailDomain_s",
    "email_address_md4": "authEmail_s",
    "author_first_name_exact": "authFirstName_s",
    # "":"authFullNameFormIDPersonIDIDHal_fs",
    # "":"authFullNameIdFormPerson_fs",
    "author_full_idhal_facet": "authFullNameIdHal_fs",
    "author_full_internal_facet": "authFullNameId_fs",
    "author_ful_full_facet": "authFullNamePersonIDIDHal_fs",
    "author_full_name_exact": "authFullName_s",
    "author_formid-personid": "authIdFormPerson_s",
    "author_internal_full_name_facet": "authIdFullName_fs",
    # "":"authIdHalFullName_fs",
    "author_idhal": "authIdHal_s",
    "author_internal_full_structprim_facet": "authIdHasPrimaryStructure_fs",
    "author_internal_full_struct_facet": "authIdHasStructure_fs",
    "author_internal_fast_first_facet": "authIdLastNameFirstName_fs",
    "author_last_first_personid_facet": "authLastNameFirstNameIdHalPersonid_fs",
    "author_last_first_exact": "authLastNameFirstName_s",
    "author_last_name_exact": "authLastName_s",
    "author_middle_name_exact": "authMiddleName_s",
    "author_funder_exact": "authOrganism_s",
    "author_job_exact": "authQuality_s",
    "auhtor_url": "authUrl_s",
    "authority_thesis_exact": "authorityInstitution_s",
    # "":"baseMap_s",
    "book_title_exact": "bookTitle_s",
    "citation_full_exact": "citationFull_s",
    "citation_abbr_exact": "citationRef_s",
    "city_exact": "city_s",
    "classification_exact": "classification_s",
    "collection_category_code_facet": "collCategoryCodeName_fs",
    "collection_category_exact": "collCategory_s",
    "collection_code_facet": "collCodeName_fs",
    "collection_code": "collCode_s",
    "collection_id_facet": "collIdName_fs",
    "collection_code_child_facet": "collIsChildOfColl_fs",
    "collection_code_category_parent_facet": "collIsParentOfCategoryColl_fs",
    "collection_code_parent_facet": "collIsParentOfColl_fs",
    "collection_name_code_facet": "collNameCode_fs",
    "collection_name_id_facet": "collNameId_fs",
    "collection_name_exact": "collName_s",
    "collab_exact": "collaboration_s",
    "comment_exact": "comment_s",
    "committee_exact": "committee_s",
    "conf_end_date": "conferenceEndDate_s",
    "conf_organizer_exact": "conferenceOrganizer_s",
    "conf_start_date": "conferenceStartDate_s",
    "conf_title_exact": "conferenceTitle_s",
    "contributor_name_internal_facet": "contributorFullNameId_fs",
    "contributor_full_name_exact": "contributorFullName_s",
    "contributor_internal_name_facet": "contributorIdFullName_fs",
    "gps_coordinates": "coordinates_s",
    "country_exact": "country_s",
    "credit_exact": "credit_s",
    "defense_date": "defenseDate_s",
    "degree_exact": "degreeType_s",
    "department_acronym_exact": "deptStructAcronym_s",
    "department_address": "deptStructAddress_s",
    "department_code_exact": "deptStructCode_s",
    "department_country": "deptStructCountry_s",
    "department_idhal_name_facet": "deptStructIdName_fs",
    "department_child_facet": "deptStructIsChildOf_fs",
    "department_parent_facet": "deptStructIsParentOf_fs",
    "department_name_id_facet": "deptStructNameId_fs",
    "department_one_name_facet": "deptStructName_fs",
    "department_name_exact": "deptStructName_s",
    "department_type": "deptStructType_s",
    "department_validity": "deptStructValid_s",
    "description": "description_s",
    "phd_director_exact": "director_s",
    "subtype_doc": "docSubType_s",
    "type_doc": "docType_s",
    "id": "docid",
    "doi_nosep": "doiId_id",
    "doi": "doiId_s",
    "domain_all_codes": "domainAllCode_s",
    "domain_exact": "domain_s",
    "epub_date": "ePublicationDate_s",
    "ensam_id_exact": "ensamId_s",
    "europeanproject_acronym_exact": "europeanProjectAcronym_s",
    "europeanproject_callid_exact": "europeanProjectCallId_s",
    "europeanproject_date_end": "europeanProjectEndDate_s",
    "europeanproject_funding": "europeanProjectFinancing_s",
    "europeanproject_id_title_facet": "europeanProjectIdTitle_fs",
    "europeanproject_ref_exact": "europeanProjectReference_s",
    "europeanproject_date_start": "europeanProjectStartDate_s",
    "europeanproject_title_id_facet": "europeanProjectTitleId_fs",
    "europeanproject_title_exact": "europeanProjectTitle_s",
    "europeanproject_validity": "europeanProjectValid_s",
    "annexe_audio": "fileAnnexesAudio_s",
    "annexe_figure": "fileAnnexesFigure_s",
    "annexe_video": "fileAnnexesVideo_s",
    "annexe_urls": "fileAnnexes_s",
    "annexe_url_main": "fileMainAnnex_s",
    "file_url_main": "fileMain_s",
    "file_type": "fileType_s",
    "file_urls": "files_s",
    "funding_exact": "funding_s",
    "doc_idhal_old": "halIdSameAs_s",
    "doc_idhal": "halId_s",
    "hec_ranking_exact": "hec_ranking_s",
    "period_historic_exact": "historicalPeriod_s",
    "image_type_exact": "imageType_s",
    "in_press_bool": "inPress_bool",
    # "":"inputType_s",
    # "":"inraeThesaurusAltLabel_local_s",
    # "":"inraeThesaurusCode_local_s",
    # "":"inraeThesaurusPrefLabel_local_s",
    "structure_acronym_exact": "instStructAcronym_s",
    "structure_address": "instStructAddress_s",
    "structure_code_exact": "instStructCode_s",
    "structure_country": "instStructCountry_s",
    "structure_id_name_facet": "instStructIdName_fs",
    "structure_id": "instStructId_i",
    "structure_child_facet": "instStructIsChildOf_fs",
    "structure_parent_facet": "instStructIsParentOf_fs",
    "structure_name_id_facet": "instStructNameId_fs",
    "structure_one_name_facet": "instStructName_fs",
    "structure_name_exact": "instStructName_s",
    "structure_type": "instStructType_s",
    "structure_validity": "instStructValid_s",
    "hal_instance": "instance_s",
    "invited_communication_exact": "invitedCommunication_s",
    # "":"irThesaurusAcronym_s",
    # "":"irThesaurusId_s",
    # "":"irThesaurusName_s",
    "ird_id_exact": "irdId_s",
    "irstea_id_exact": "irsteaId_s",
    "isbn_unsensitive": "isbn_s",
    "isbn": "isbn_s",
    "issue_number": "issue_s",
    "classification_jel_exact": "jel_s",
    "journal_date": "journalDate_s",
    "journal_doi_root": "journalDoiRoot_s",
    "journal_eissn": "journalEissn_s",
    "journal_id_title_facet": "journalIdTitle_fs",
    "journal_issn": "journalIssn_s",
    "journal_publisher_exact": "journalPublisher_s",
    "journal_sherpa_color": "journalSherpaColor_s",
    "journal_sherpa_condition": "journalSherpaCondition_s",
    "journal_sherpa_date": "journalSherpaDate_s",
    "journal_sherpa_post_authorisations": "journalSherpaPostPrint_s",
    "journal_sherpa_post_restrictions": "journalSherpaPostRest_s",
    "journal_sherpa_": "journalSherpaPrePrint_s",
    "journal_sherpa_": "journalSherpaPreRest_s",
    "journal_title_abbe_exact": "journalTitleAbbr_s",
    "journal_title_name_id_facet": "journalTitleId_fs",
    "journal_title_exact": "journalTitle_s",
    "journal_url": "journalUrl_s",
    "journal_validity": "journalValid_s",
    "journal_multi": "journal_t",
    "keyword_exact": "keyword_s",
    # "":"laas_directorEmail_s",
    # "":"laas_renatech_s",
    "lab_acronym_exact": "labStructAcronym_s",
    "lab_address": "labStructAddress_s",
    "lab_code_exact": "labStructCode_s",
    "lab_country": "labStructCountry_s",
    "lab_id_name_facet": "labStructIdName_fs",
    "lab_child_facet": "labStructIsChildOf_fs",
    "lab_parent_facet": "labStructIsParentOf_fs",
    "lab_name_id_facet": "labStructNameId_fs",
    "lab_": "labStructName_fs",
    "lab_name_exact": "labStructName_s",
    "lab_type": "labStructType_s",
    "lab_validity": "labStructValid_s",
    "label_bibtex": "label_bibtex",
    "label_coins": "label_coins",
    "label_endnote": "label_endnote",
    "label_ref": "label_s",
    "label_xml": "label_xml",
    "language_format_exact": "language_s",
    "lecture_name": "lectureName_s",
    "lecture_level_exact": "lectureType_s",
    # "":"length_i",
    "licence_exact": "licence_s",
    "licence_unsensitive": "licence_t",
    "licence": "licence_t",
    "external_id_exact": "linkExtId_s",
    "external_id_unsensitive": "linkExtUrl_s",
    "external_id": "linkExtUrl_s",
    "internal_ref_exact": "localReference_s",
    "gps_coordinates": "location",
    "classification_mesh_exact": "mesh_s",
    "modification_date": "modifiedDate_s",
    "phd_number_s": "nntId_s",
    "number_s": "number_s",
    "oatao_s": "oataoId_s",
    # "":"oldDocType_s",
    "open_access_bool": "openAccess_bool",
    "other_type": "otherType_s",
    # "":"overlayService_s",
    "page": "page_s",
    "peer_reviewing_exact": "peerReviewing_s",
    "popular_exact": "popularLevel_s",
    "primary_domain": "primaryDomain_s",
    "proceedings_exact": "proceedings_s",
    "production_date": "producedDate_s",
    "publication_date": "publicationDate_s",
    "publication_date_format": "publicationDate_tdate",
    "publication_location_exact": "publicationLocation_s",
    "publisher_link": "publisherLink_s",
    "publisher_exact": "publisher_s",
    "pubmed_id_s": "pubmedId_s",
    "release_date": "releasedDate_s",
    "report_type_exact": "reportType_s",
    "grp_struct_acronym_exact": "rgrpInstStructAcronym_s",
    "grp_struct_address": "rgrpInstStructAddress_s",
    "grp_struct_code_exact": "rgrpInstStructCode_s",
    "grp_struct_country": "rgrpInstStructCountry_s",
    "grp_struct_id_name_facet": "rgrpInstStructIdName_fs",
    "grp_struct_child_facet": "rgrpInstStructIsChildOf_fs",
    "grp_struct_parent_facet": "rgrpInstStructIsParentOf_fs",
    "grp_struct_name_id_facet": "rgrpInstStructNameId_fs",
    "grp_struct_name_id_facetb": "rgrpInstStructName_fs",
    "grp_struct_name_exact": "rgrpInstStructName_s",
    "grp_struct_name_ex_unsensitive": "rgrpInstStructName_sci",
    "grp_struct_name_unsensitive": "rgrpInstStructName_t",
    "grp_struct_name": "rgrpInstStructName_t",
    "grp_struct_type": "rgrpInstStructType_s",
    "grp_struct_validity": "rgrpInstStructValid_s",
    "grp_lab_acronym_exact": "rgrpLabStructAcronym_s",
    "grp_lab_address": "rgrpLabStructAddress_s",
    "grp_lab_code_exact": "rgrpLabStructCode_s",
    "grp_lab_country": "rgrpLabStructCountry_s",
    "grp_lab_id_name_facet": "rgrpLabStructIdName_fs",
    "grp_lab_child_facet": "rgrpLabStructIsChildOf_fs",
    "grp_lab_parent_facet": "rgrpLabStructIsParentOf_fs",
    "grp_lab_name_id_facet": "rgrpLabStructNameId_fs",
    "grp_lab_name_id_facetb": "rgrpLabStructName_fs",
    "grp_lab_name_exact": "rgrpLabStructName_s",
    "grp_lab_type": "rgrpLabStructType_s",
    "grp_lab_validity": "rgrpLabStructValid_s",
    "team_acronym_exact": "rteamStructAcronym_s",
    "team_address": "rteamStructAddress_s",
    "team_code_exact": "rteamStructCode_s",
    "team_country": "rteamStructCountry_s",
    "team_id_name": "rteamStructIdName_fs",
    "team_child_facet": "rteamStructIsChildOf_fs",
    "team_parent_facet": "rteamStructIsParentOf_fs",
    "team_name_id_facet": "rteamStructNameId_fs",
    "team_name_id_facetb": "rteamStructName_fs",
    "team_name_exact": "rteamStructName_s",
    "team_type": "rteamStructType_s",
    "team_validity": "rteamStructValid_s",
    "scale_exact": "scale_s",
    "science_po_id_s": "sciencespoId_s",
    "scientific_editor_exact": "scientificEditor_s",
    "see_also": "seeAlso_s",
    "self_archiving_bool": "selfArchiving_bool",
    "serie_title_exact": "serie_s",
    "serie_editor_exact": "seriesEditor_s",
    "soft_code_repository_exact": "softCodeRepository_s",
    "soft_dev_status_exact": "softDevelopmentStatus_s",
    "soft_platform_exact": "softPlatform_s",
    "soft_language_": "softProgrammingLanguage_s",
    "soft_run_platform_": "softRuntimePlatform_s",
    "soft_version_": "softVersion_s",
    "source": "source_s",
    "struct_acronym_exact": "structAcronym_s",
    "struct_address": "structAddress_s",
    "struct_code_exact": "structCode_s",
    "struct_country_exact": "structCountry_s",
    # "struct_":"structHasAlphaAuthIdHalPersonid_fs",
    # "struct_":"structHasAlphaAuthIdHal_fs",
    "struct_name_id_name_id_facet": "structHasAlphaAuthId_fs",
    # "struct_":"structHasAuthIdHalPersonid_s",
    # "struct_":"structHasAuthIdHal_fs",
    "struct_id_name_id_name_facet": "structHasAuthId_fs",
    "struct_id_name_facet": "structIdName_fs",
    "struct_child_facet": "structIsChildOf_fs",
    # "struct_":"structIsParentOfType_fs",
    "struct_parent_facet": "structIsParentOf_fs",
    "struct_one_id_facet": "structNameId_fs",
    "struct_name_facet": "structName_fs",
    "struct_name_exact": "structName_s",
    # "struct_":"structPrimaryHasAlphaAuthIdHalPersonid_fs",
    # "struct_":"structPrimaryHasAlphaAuthIdHal_fs",
    # "struct_":"structPrimaryHasAlphaAuthId_fs",
    # "struct_":"structPrimaryHasAuthIdHal_fs",
    # "struct_":"structPrimaryHasAuthId_fs",
    "struct_type": "structType_s",
    "struct_validity": "structValid_s",
    "subtitle_exact": "subTitle_s",
    "type": "submitType_s",
    "submit_date": "submittedDate_s",
    "thesis_school_exact": "thesisSchool_s",
    "title_exact": "title_s",
    "title": "title_s",
    "annexe_type_exact": "typeAnnex_s",
    "type_exact": "type_s",
    "uri": "uri_s",
    # "":"urlFulltextEsr_s",
    "volume": "volume_s",
    "writing_date": "writingDate_s",
}
# https://api.archives-ouvertes.fr/docs/search/?#wt
HAL_API_ALLOWED_RETURN_FORMATS_DOC = ["json",
                                    "xml",
                                    "xml-tei",
                                    "bibtex",
                                    "endnote",
                                    "rss",
                                    "atom",
                                    "csv"]
HAL_API_DEFAULT_QUERY_TYPE_DOC = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_DOC = "json"
## ANR
# https://api.archives-ouvertes.fr/docs/ref/resource/anrproject
# https://api.archives-ouvertes.fr/docs/ref/?resource=anrproject&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_ANR = {
    "acronym_type_exact": "acronymProgram_s",
    "acronym_type_ex_unsensitive": "acronymProgram_sci",
    "acronym_type_unsensitive": "acronymProgram_t",
    "acronym_type": "acronymProgram_t",
    "acronym_exact": "acronym_s",
    "acronym_ex_unsensitive": "acronym_sci",
    "acronym_unsensitive": "acronym_t",
    "acronym": "acronym_t",
    "calltitle_full_format": "callTitle_fs",
    "calltitle_exact": "callTitle_s",
    "calltitle_ex_unsensitive": "callTitle_sci",
    "calltitle_unsensitive": "callTitle_t",
    "calltitle": "callTitle_t",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "label_html": "label_html",
    "title_display": "label_s",
    "ref_project_exact": "reference_s",
    "ref_project_ex_unsensitive": "reference_sci",
    "ref_project_unsensitive": "reference_t",
    "ref_project": "reference_t",
    "text_search_unsensitive": "text",
    "text_search": "text",
    "text_search_auto_complete": "text_autocomplete",
    "title_exact": "title_s",
    "title_exact_unsensitive": "title_sci",
    "title_unsensitive": "title_t",
    "title": "title_t",
    "validity": "valid_s",
    "validity_date": "yearDate_s",
    "validity_date_format": "yearDate_tdate",
}
HAL_API_ALLOWED_RETURN_FIELDS_ANR = {
    "acronym_type_exact": "acronymProgram_s",
    "acronym_exact": "acronym_s",
    "calltitle_full_format": "callTitle_fs",
    "calltitle_exact": "callTitle_s",
    "calltitle": "callTitle_s",
    "id": "docid",
    "label_html": "label_html",
    "title_abb_format": "label_s",
    "ref_project_exact": "reference_s",
    "title_exact": "title_s",
    "title": "title_s",
    "validity": "valid_s",
    "validity_date": "yearDate_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=anrproject#wt
HAL_API_ALLOWED_RETURN_FORMATS_ANR = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_ANR = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_ANR = "json"
## EUROPEANPROJECT
# https://api.archives-ouvertes.fr/docs/ref/resource/europeanproject
# https://api.archives-ouvertes.fr/docs/ref/?resource=europeanproject&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_EUROPEANPROJECT = {
    "acronym_exact": "acronym_s",
    "acronym_ex_unsensitive": "acronym_sci",
    "acronym_unsensitive": "acronym_t",
    "acronym": "acronym_t",
    "num_project_exact": "callId_s",
    "num_project_ex_unensensitive": "callId_sci",
    "num_project_unsensitive": "callId_t",
    "num_project": "callId_t",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "end_date": "endDate_s",
    "end_date_format": "endDate_tdate",
    "funding_type_exact": "financing_s",
    "funding_type_unsensitive": "financing_t",
    "funding_type": "financing_t",
    "label_html": "label_html",
    "title_display": "label_s",
    "id_openaire_exact": "openaireId_s",
    "openaire_bool": " openaire_bool ",
    "ref_project_exact": "reference_s",
    "ref_project_ex_unsensitive": "reference_sci",
    "ref_project_unsensitive": "reference_t",
    "ref_project": "reference_t",
    "start_date": "startDate_s",
    "start_date_format": "startDate_tdate",
    "text_search_unsensitive": "text",
    "text_search": "text",
    "text_search_auto_complete": "text_autocomplete",
    "title_exact": "title_s",
    "title_exact_unsensitive": "title_sci",
    "title_unsensitive": "title_t",
    "title": "title_t",
    "validity": "valid_s",
}
HAL_API_ALLOWED_RETURN_FIELDS_EUROPEANPROJECT = {
    "acronym_exact": "acronym_s",
    "num_project_exact": "callId_s",
    "id": "docid",
    "end_date": "endDate_s",
    "funding_type_exact": "financing_s",
    "label_html": "label_html",
    "title_display": "label_s",
    "id_openaire_exact": "openaireId_s",
    "openaire_bool": "openaire_bool",
    "ref_project_exact": "reference_s",
    "start_date": "startDate_s",
    "title_exact": "title_s",
    "title": "title_s",
    "validity": "valid_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=europeanproject#wt
HAL_API_ALLOWED_RETURN_FORMATS_EUROPEANPROJECT = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_EUROPEANPROJECT = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_EUROPEANPROJECT = "json"
## DOMAIN
# https://api.archives-ouvertes.fr/docs/ref/resource/domain
# https://api.archives-ouvertes.fr/docs/ref/?resource=domain&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_DOMAIN = {
    "domain_code": "code_s",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "has_child": "haveNext_bool",
    "title_display": "label_s",
    "domain_level": "level_i",
    "id_parent": "parent_i",
    "text_search_unsensitive": "text",
    "text_search": "text",
}
HAL_API_ALLOWED_RETURN_FIELDS_DOMAIN = {
    "domain_code": "code_s",
    "id": "docid",
    "has_child": "haveNext_bool",
    "title_display": "label_s",
    "title": "label_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=domain#wt
HAL_API_ALLOWED_RETURN_FORMATS_DOMAIN = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_DOMAIN = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_DOMAIN = "json"
## AUTHOR
# https://api.archives-ouvertes.fr/docs/ref/resource/author
# https://api.archives-ouvertes.fr/docs/ref/?resource=author&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_AUTHOR = {
    "account_associated": "accountAssociated_bool",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "email_domain": "emailDomain_s",
    "email": "emailId_t",
    "first_name_exact": "firstName_s",
    "firt_name_unsensitive": "firstName_t",
    "firt_name": "firstName_t",
    "full_name_auto_complete": "fullName_autocomplete",
    "full_name_exact": "fullName_s",
    "full_name_exact_unsensitive": "fullName_sci",
    "full_name_unsensitive": "fullName_t",
    "full_name": "fullName_t",
    "has_cv": "hasCV_bool",
    "idhal_num": "idHal_i",
    "idhal": "idHal_s",
    "label_html": "label_html",
    "full_name_disp": "label_s",
    "last_name_exact": "lastName_s",
    "last_name_unsensitive": "lastName_t",
    "last_name_": "lastName_t",
    "middle_name_exact": "middleName_s",
    "middle_name_unsensitive": "middleName_t",
    "middle_name": "middleName_t",
    "text_search_unsensitive": "text",
    "text_search": "text",
    "text_search_auto_complete": "text_autocomplete",
    "validity": "valid_s",
    "ids_ext": "Id_id",
    "ids_ext_exact": "Id_s",
}
HAL_API_ALLOWED_RETURN_FIELDS_AUTHOR = {
    "account_associated": "accountAssociated_bool",
    "id": "docid",
    "email_domain": "emailDomain_s",
    "first_name_exact": "firstName_s",
    "full_nome_format": "fullNameDocid_fs",
    "full_name_exact": "fullName_s",
    "has_cv": "hasCV_bool",
    "idhal": "idHal_s",
    "label_html": "label_html",
    "full_name_disp": "label_s",
    "last_name_exact": "lastName_s",
    "middle_name_exact": "middleName_s",
    "validity": "valid_s",
    "ids_ext_exact": "Id_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=author#wt
HAL_API_ALLOWED_RETURN_FORMATS_AUTHOR = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_AUTHOR = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_AUTHOR = "json"
## JOURNAL
# https://api.archives-ouvertes.fr/docs/ref/resource/journal
# https://api.archives-ouvertes.fr/docs/ref/?resource=journal&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_JOURNAL = {
    "id_merged": "aliasDocid_i",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "doi_root": "doiRoot_s",
    "eissn": "eissn_s",
    "end_date": "endDate_s",
    "end_date_format": "endDate_tdate",
    "issn": "issn_s",
    "label_html": "label_html",
    "full_name_disp": "label_s",
    "publisher_name_exact": "publisher_s",
    "publisher_name_ex_unsensitive": "publisher_sci",
    "publisher_name_unsensitive": "publisher_t",
    "publisher_name": "publisher_t",
    "sherpa_color": "sherpaColor_s",
    "sherpa_conditions": "sherpaCondition_s",
    "sherpa_update_date": "sherpaDate_s",
    "sherpa_update_date_format": "sherpaDate_tdate",
    "post_print_authorisations": "sherpaPostPrint_s",
    "port_print_restrictions": "sherpaPostRest_s",
    "pre_print_authorisations": "sherpaPrePrint_s",
    "pre_print_restrictions": "sherpaPreRest_s",
    "start_date_publishing": "startDate_s",
    "start_date_publishing_format": "startDate_tdate",
    "text_search_unsensitive": "text",
    "text_search": "text",
    "text_search_auto_complete": "text_autocomplete",
    "title_abbr_exact": "titleAbbr_s",
    "title_abbr_exact_unsensitive": "titleAbbr_sci",
    "title_abbr_unsensitive": "titleAbbr_t",
    "title_abbr": "titleAbbr_t",
    "title_search_auto_complete": "title_autocomplete",
    "title_exact": "title_s",
    "title_exact_unsensitive": "title_sci",
    "title_unsensitive": "title_t",
    "title": "title_t",
    "update_date": "updateDate_s",
    "update_date_format": "updateDate_tdate",
    "url": "url_s",
    "validity": "valid_s",
}
HAL_API_ALLOWED_RETURN_FIELDS_JOURNAL = {
    "id_merge_journal": "aliasDocid_i",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "doi_root": "doiRoot_s",
    "eissn": "eissn_s",
    "end_date": "endDate_s",
    "end_date_format": "endDate_tdate",
    "issn": "issn_s",
    "label_html": "label_html",
    "full_name_disp": "label_s",
    "publisher_name_exact": "publisher_s",
    "sherpa_color": "sherpaColor_s",
    "sherpa_conditions": "sherpaCondition_s",
    "sherpa_update_date": "sherpaDate_s",
    "sherpa_update_date_format": "sherpaDate_tdate",
    "post_print_authorisations": "sherpaPostPrint_s",
    "port_print_restrictions": "sherpaPostRest_s",
    "pre_print_authorisations": "sherpaPrePrint_s",
    "pre_print_restrictions": "sherpaPreRest_s",
    "start_date_publishing": "startDate_s",
    "start_date_publishing_format": "startDate_tdate",
    "title_abbr_exact": "titleAbbr_s",
    "title_exact": "title_s",
    "title": "title_s",
    "update_date": "updateDate_s",
    "update_date_format": "updateDate_tdate",
    "url": "url_s",
    "validity": "valid_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=journal#wt
HAL_API_ALLOWED_RETURN_FORMATS_JOURNAL = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_JOURNAL = "title_search_auto_complete"
HAL_API_DEFAULT_RETURN_FORMAT_JOURNAL = "json"
# AUTHORSTRUCTURE
# https://api.archives-ouvertes.fr/docs/ref/resource/authorstructure
HAL_API_ALLOWED_QUERY_TYPES_AUTHORSTRUCTURE = {
    "last_name": "lastName_t",
    "first_name": "firstName_t",
    "email": "email_s",
    "production_year": "producedDateY_i",
    "deviation_year": "deviation",
    "get_parents": "getParents",
}
HAL_API_ALLOWED_RETURN_FIELDS_AUTHORSTRUCTURE = {}
HAL_API_ALLOWED_RETURN_FORMATS_AUTHORSTRUCTURE = ["json", "xml"]
HAL_API_DEFAULT_QUERY_TYPE_AUTHORSTRUCTURE = "last_name"
HAL_API_DEFAULT_RETURN_FORMAT_AUTHORSTRUCTURE = "json"
## STRUCTURE
# https://api.archives-ouvertes.fr/docs/ref/resource/structure
# https://api.archives-ouvertes.fr/docs/ref/?resource=structure&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_STRUCTURE = {
    "acronym_exact": "acronym_s",
    "acronym_ex_unsensitive": "acronym_sci",
    "acronym_unsensitive": "acronym_t",
    "acronym": "acronym_t",
    "address_exact": "address_s",
    "address_unsensitive": "address_t",
    "address": "address_t",
    # "":"aliasDocid_i",
    "code_unit_exact": "code_s",
    "code_unit_ex_unsensitive": "code_sci",
    "code_unit_unsensitive": "code_t",
    "code_unit_": "code_t",
    "country_exact": "country_s",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "label_html": "label_html",
    "label_exact": "label_s",
    "label_ex_unsensitive": "label_sci",
    "label_format_xml": "label_xml",
    "locked_structure": "locked_bool",
    "name_exact": "name_s",
    "name_ex_unsensitive": "name_sci",
    "name_unsensitive": "name_t",
    "name": "name_t",
    "parent_acronym_exact": "parentAcronym_s",
    "parent_acronym_unsensitive": "parentAcronym_t",
    "parent_acronym": "parentAcronym_t",
    "parent_address_exact": "parentAddress_s",
    "parent_country_exact": "parentCountry_s",
    "parent_id": "parentDocid_i",
    "parent_name_exact": "parentName_s",
    "parent_name_unsensitive": "parentName_t",
    "parent_name_": "parentName_t",
    "parent_type_exact": "parentType_s",
    "parent_update_date": "parentUpdateDate_s",
    "parent_update_date_format": "parentUpdateDate_tdate",
    "parent_url": "parentUrl_s",
    "parent_valid": "parentValid_s",
    "text_search_unsensitive": "text",
    "text_search": "text",
    "text_search_auto_complete": "text_autocomplete",
    "type_exact": "type_s",
    "update_date": "updateDate_s",
    "update_date_format": "updateDate_tdate",
    "url": "url_s",
    "validity": "valid_s",
}
HAL_API_ALLOWED_RETURN_FIELDS_STRUCTURE = {
    "acronym_exact": "acronym_s",
    "address_exact": "address_s",
    "code_unit_exact": "code_s",
    "country_exact": "country_s",
    "id": "docid",
    "label_html": "label_html",
    "label_exact": "label_s",
    "label_format_xml": "label_xml",
    "locked_structure": "locked_bool",
    "name_exact": "name_s",
    "parent_acronym_exact": "parentAcronym_s",
    "parent_address_exact": "parentAddress_s",
    "parent_country_exact": "parentCountry_s",
    "parent_id": "parentDocid_i",
    "parent_name_exact": "parentName_s",
    "parent_type_exact": "parentType_s",
    "parent_update_date": "parentUpdateDate_s",
    "parent_url": "parentUrl_s",
    "parent_valid": "parentValid_s",
    "type_exact": "type_s",
    "update_date": "updateDate_s",
    "url": "url_s",
    "validity": "valid_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=structure#wt
HAL_API_ALLOWED_RETURN_FORMATS_STRUCTURE = ["json", "xml", "xml-tei", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_STRUCTURE = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_STRUCTURE = "json"
## DOCTYPE
# https://api.archives-ouvertes.fr/docs/ref/resource/doctype
HAL_API_ALLOWED_QUERY_TYPES_DOCTYPE = {
    "instance_name_exact": "instance_s",
    "lang": "lang",
}
HAL_API_ALLOWED_RETURN_FIELDS_DOCTYPE = {}
HAL_API_ALLOWED_RETURN_FORMATS_DOCTYPE = ["json", "xml"]
HAL_API_DEFAULT_QUERY_TYPE_DOCTYPE = "instance_name_exact"
HAL_API_DEFAULT_RETURN_FORMAT_DOCTYPE = "json"
## INSTANCE
# https://api.archives-ouvertes.fr/docs/ref/resource/instance
HAL_API_ALLOWED_QUERY_TYPES_INSTANCE = {}
HAL_API_ALLOWED_RETURN_FIELDS_INSTANCE = {}
HAL_API_ALLOWED_RETURN_FORMATS_INSTANCE = ["json", "xml"]
HAL_API_DEFAULT_QUERY_TYPE_INSTANCE = ""
HAL_API_DEFAULT_RETURN_FORMAT_INSTANCE = "json"
## METADATA
# https://api.archives-ouvertes.fr/docs/ref/resource/metadata
HAL_API_ALLOWED_QUERY_TYPES_METADATA = {
    "instance_name_exact": "instance_s",
    "type_doc": "docType_s",
    "lang": "lang",
}
HAL_API_ALLOWED_RETURN_FIELDS_METADATA = {}
HAL_API_ALLOWED_RETURN_FORMATS_METADATA = ["xml"] # ["json", "xml"] (json not working)
HAL_API_DEFAULT_QUERY_TYPE_METADATA = "instance_name_exact"
HAL_API_DEFAULT_RETURN_FORMAT_METADATA = "xml"
## METADATALIST
# https://api.archives-ouvertes.fr/docs/ref/?resource=metadatalist&schema=fields#fields
HAL_API_ALLOWED_QUERY_TYPES_METADATALIST = {
    "id_merged": "aliasDocid_i",
    "date_last_indexed": "dateLastIndexed_tdate",
    "id": "docid",
    "label_exact": "label_s",
    "metalabel_exact": "metaLabel_s",
    "metalabel_ex_unsensitive": "metaLabel_sci",
    "metalabel_unsensitive": "metaLabel_t",
    "metalabel": "metaLabel_t",
    "meta_name_exact": "metaName_s",
    "meta_name_unsensitive": "metaName_t",
    "meta_name": "metaName_t",
    "meta_value_exact": "metaValue_s",
    "meta_value_unsensitive": "metaValue_t",
    "meta_value": "metaValue_t",
    "text_search_unsensitive": "text",
    "text_search": "text",
}
HAL_API_ALLOWED_RETURN_FIELDS_METADATALIST = {
    "id": "docid",
    "label_exact": "label_s",
    "metalabel_exact": "metaLabel_s",
    "meta_name_exact": "metaName_s",
    "meta_value_exact": "metaValue_s",
}
# https://api.archives-ouvertes.fr/docs/ref/?resource=metadatalist#wt
HAL_API_ALLOWED_RETURN_FORMATS_METADATALIST = ["json", "xml", "csv"]
HAL_API_DEFAULT_QUERY_TYPE_METADATALIST = "text_search_unsensitive"
HAL_API_DEFAULT_RETURN_FORMAT_METADATALIST = "json"
############################################################
############################################################
############################################################
## full fields/query/return types for HAL API
HAL_API_ALLOWED_QUERY_TYPES = (
    HAL_API_ALLOWED_QUERY_TYPES_JOURNAL
    | HAL_API_ALLOWED_QUERY_TYPES_DOMAIN
    | HAL_API_ALLOWED_QUERY_TYPES_EUROPEANPROJECT
    | HAL_API_ALLOWED_QUERY_TYPES_STRUCTURE
    | HAL_API_ALLOWED_QUERY_TYPES_AUTHOR
    | HAL_API_ALLOWED_QUERY_TYPES_ANR
    | HAL_API_ALLOWED_QUERY_TYPES_DOCTYPE
    | HAL_API_ALLOWED_QUERY_TYPES_INSTANCE
    | HAL_API_ALLOWED_QUERY_TYPES_METADATA
    | HAL_API_ALLOWED_QUERY_TYPES_METADATALIST
    | HAL_API_ALLOWED_QUERY_TYPES_AUTHORSTRUCTURE
    | HAL_API_ALLOWED_QUERY_TYPES_DOC
)
HAL_API_ALLOWED_RETURN_FIELDS = (
    HAL_API_ALLOWED_RETURN_FIELDS_JOURNAL
    | HAL_API_ALLOWED_RETURN_FIELDS_DOMAIN
    | HAL_API_ALLOWED_RETURN_FIELDS_EUROPEANPROJECT
    | HAL_API_ALLOWED_RETURN_FIELDS_STRUCTURE
    | HAL_API_ALLOWED_RETURN_FIELDS_AUTHOR
    | HAL_API_ALLOWED_RETURN_FIELDS_ANR
    | HAL_API_ALLOWED_RETURN_FIELDS_DOCTYPE
    | HAL_API_ALLOWED_RETURN_FIELDS_INSTANCE
    | HAL_API_ALLOWED_RETURN_FIELDS_METADATA
    | HAL_API_ALLOWED_RETURN_FIELDS_METADATALIST
    | HAL_API_ALLOWED_RETURN_FIELDS_AUTHORSTRUCTURE
    | HAL_API_ALLOWED_RETURN_FIELDS_DOC
)
HAL_API_ALLOWED_RETURN_FORMATS = list(set(
    HAL_API_ALLOWED_RETURN_FORMATS_DOMAIN
    + HAL_API_ALLOWED_RETURN_FORMATS_JOURNAL
    + HAL_API_ALLOWED_RETURN_FORMATS_EUROPEANPROJECT
    + HAL_API_ALLOWED_RETURN_FORMATS_STRUCTURE
    + HAL_API_ALLOWED_RETURN_FORMATS_AUTHOR
    + HAL_API_ALLOWED_RETURN_FORMATS_ANR
    + HAL_API_ALLOWED_RETURN_FORMATS_DOCTYPE
    + HAL_API_ALLOWED_RETURN_FORMATS_INSTANCE
    + HAL_API_ALLOWED_RETURN_FORMATS_METADATA
    + HAL_API_ALLOWED_RETURN_FORMATS_METADATALIST
    + HAL_API_ALLOWED_RETURN_FORMATS_AUTHORSTRUCTURE
    + HAL_API_ALLOWED_RETURN_FORMATS_DOC
))
HAL_API_DEFAULT_QUERY_TYPE = HAL_API_DEFAULT_QUERY_TYPE_DOC
HAL_API_DEFAULT_RETURN_FORMAT = HAL_API_DEFAULT_RETURN_FORMAT_DOC
############################################################
############################################################
############################################################

HAL_TEI_URL = "https://api.archives-ouvertes.fr/oai/TEI/{hal_id}"
HAL_SWORD_API_URL = furl("https://api.archives-ouvertes.fr/sword/hal/")
HAL_SWORD_PRE_API_URL = furl("https://api-preprod.archives-ouvertes.fr/sword/hal/")

ID_ORCID_URL = furl("http://orcid.org/")
ID_ARXIV_URL = furl("http://arxiv.org/a/")
ID_RESEARCHERID_URL = furl("http://www.researcherid.com/rid/")
ID_IDREF_URL = furl("http://www.idref.fr/")
ID_CC_URL = furl("https://creativecommons.org/licenses/")

DEFAULT_AUDIENCE = "1"
DEFAULT_INVITED = "0"
DEFAULT_POPULAR = "0"
DEFAULT_PEER = "0"
DEFAULT_PROCEEDINGS = "0"
DEFAULT_STRUCT_TYPE = "institution"
DEFAULT_LANG_DOC = "en"
